# config.yml

tuic_port: ""                  #输入端口=确认部署
hy2_port: ""                   #输入端口=确认部署
reality_port: ""               #输入端口=确认部署
sni: "www.bing.com"
debug: false
nezha_server: ""
nezha_key: ""
uuid: ""